Rails 6.1にあげてみた
次はこれの解消

```
An error occurred while loading ./spec/mailers/user_mailer_spec.rb.
Failure/Error: add_template_helper(ApplicationHelper)

NoMethodError:
  undefined method `add_template_helper' for UserMailer:Class
# /usr/local/bundle/gems/actionmailer-6.1.7.10/lib/action_mailer/base.rb:589:in `method_missing'
# ./app/mailers/user_mailer.rb:4:in `<class:UserMailer>'
# ./app/mailers/user_mailer.rb:2:in `<top (required)>'
# /usr/local/bundle/gems/activesupport-6.1.7.10/lib/active_support/dependencies.rb:332:in `require'
# /usr/local/bundle/gems/activesupport-6.1.7.10/lib/active_support/dependencies.rb:332:in `block in require'
# /usr/local/bundle/gems/activesupport-6.1.7.10/lib/active_support/dependencies.rb:299:in `load_dependency'
# /usr/local/bundle/gems/activesupport-6.1.7.10/lib/active_support/dependencies.rb:332:in `require'
# /usr/local/bundle/gems/activesupport-6.1.7.10/lib/active_support/dependencies.rb:424:in `block in require_or_load'
# /usr/local/bundle/gems/activesupport-6.1.7.10/lib/active_support/dependencies.rb:39:in `block in load_interlock'
# /usr/local/bundle/gems/activesupport-6.1.7.10/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
# /usr/local/bundle/gems/activesupport-6.1.7.10/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
# /usr/local/bundle/gems/activesupport-6.1.7.10/lib/active_support/dependencies/interlock.rb:13:in `loading'
# /usr/local/bundle/gems/activesupport-6.1.7.10/lib/active_support/dependencies.rb:39:in `load_interlock'
# /usr/local/bundle/gems/activesupport-6.1.7.10/lib/active_support/dependencies.rb:402:in `require_or_load'
# /usr/local/bundle/gems/activesupport-6.1.7.10/lib/active_support/dependencies.rb:558:in `load_missing_constant'
# /usr/local/bundle/gems/activesupport-6.1.7.10/lib/active_support/dependencies.rb:213:in `const_missing'
# ./spec/mailers/user_mailer_spec.rb:4:in `<top (required)>'
# /usr/local/bundle/gems/activesupport-6.1.7.10/lib/active_support/dependencies.rb:326:in `load'
# /usr/local/bundle/gems/activesupport-6.1.7.10/lib/active_support/dependencies.rb:326:in `block in load'
# /usr/local/bundle/gems/activesupport-6.1.7.10/lib/active_support/dependencies.rb:299:in `load_dependency'
# /usr/local/bundle/gems/activesupport-6.1.7.10/lib/active_support/dependencies.rb:326:in `load'
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Finished in 0.00004 seconds (files took 1.74 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```